### ISSUE TITLE
deno node compatibility issues

### ISSUE THREAD

**Issue by JohannesMerkt** [LukeChannings/docker-deno#16]
I have a build action that always fails due to node compatibilty libraries missing. Is there anything I do wrong?
![grafik](https://user-images.githubusercontent.com/25324640/225345279-ccf29270-94e0-4664-b765-4cd3e1e6bd45.png)
The dockerfile is very simple: 
```Dockerfile
FROM lukechannings/deno:latest

EXPOSE 3000

WORKDIR /app

COPY . .
RUN deno cache main.ts

CMD ["run", "--allow-read", "--allow-write", "--allow-env", "--allow-net", "main.ts"]
```
And so is the github action:
```yaml
name: Build and Push Image to registry
on:
  release:
    types: [created]

permissions: 
  packages: write
  contents: read
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
```
